const { getDb } = require("./mongoClient");
const subjects = [
  {
    code: "iaf-001",
    name: "introducción a la física",
    department: "departamento de física",
    credits: 6,
    semester: 1,
    id: 1,
  },
  {
    code: "cal-001",
    name: "cálculo i",
    department: "departamento de matemática",
    credits: 6,
    semester: 1,
    id: 2,
  },
  {
    code: "alg-001",
    name: "álgebra i",
    department: "departamento de matemática",
    credits: 6,
    semester: 1,
    id: 3,
  },
  {
    code: "iue-001",
    name: "identidad, universidad, equidad y género",
    department: "escuela de educación",
    credits: 2,
    semester: 1,
    id: 4,
  },
  {
    code: "ing-001",
    name: "inglés i",
    department: "dirección general de pregrado",
    credits: 4,
    semester: 1,
    id: 5,
  },
  {
    code: "fge-001",
    name: "formación general electiva",
    department: "dirección general de pregrado",
    credits: 2,
    semester: 1,
    id: 6,
  },
  {
    code: "pii-001",
    name: "proyecto introducción a la ingeniería",
    department: "facultad de ingeniería y ciencias geológicas",
    credits: 5,
    semester: 1,
    id: 7,
  },
  {
    code: "mec-001",
    name: "mecánica",
    department: "departamento de física",
    credits: 6,
    semester: 2,
    id: 8,
  },
  {
    code: "cal-002",
    name: "cálculo ii",
    department: "departamento de matemática",
    credits: 6,
    semester: 2,
    id: 9,
  },
  {
    code: "alg-002",
    name: "álgebra ii",
    department: "departamento de matemática",
    credits: 6,
    semester: 2,
    id: 10,
  },
  {
    code: "prg-001",
    name: "programación",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 6,
    semester: 2,
    id: 11,
  },
  {
    code: "coe-001",
    name: "comunicación efectiva i",
    department: "escuela de educación",
    credits: 2,
    semester: 2,
    id: 12,
  },
  {
    code: "ing-002",
    name: "inglés ii",
    department: "dirección general de pregrado",
    credits: 4,
    semester: 2,
    id: 13,
  },
  {
    code: "ecd-001",
    name: "ecuaciones diferenciales",
    department: "departamento de matemática",
    credits: 5,
    semester: 3,
    id: 14,
  },
  {
    code: "cal-003",
    name: "cálculo iii",
    department: "departamento de matemática",
    credits: 5,
    semester: 3,
    id: 15,
  },
  {
    code: "qmc-001",
    name: "química general",
    department: "departamento de química",
    credits: 5,
    semester: 3,
    id: 16,
  },
  {
    code: "poo-001",
    name: "programación orientada a objetos",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 3,
    id: 17,
  },
  {
    code: "tpa-001",
    name: "técnicas y metodologías de programación avanzada",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 2,
    semester: 3,
    id: 18,
  },
  {
    code: "coe-002",
    name: "comunicación efectiva ii",
    department: "escuela de educación",
    credits: 2,
    semester: 3,
    id: 19,
  },
  {
    code: "dfc-001",
    name: "diálogo, fe y cultura",
    department: "departamento de teología",
    credits: 2,
    semester: 3,
    id: 20,
  },
  {
    code: "elm-001",
    name: "electro magnetismo",
    department: "departamento de física",
    credits: 6,
    semester: 4,
    id: 21,
  },
  {
    code: "est-001",
    name: "estadística",
    department: "departamento de matemática",
    credits: 6,
    semester: 4,
    id: 22,
  },
  {
    code: "ids-001",
    name: "ingeniería y desarrollo sustentable",
    department: "departamento de química",
    credits: 5,
    semester: 4,
    id: 23,
  },
  {
    code: "epr-001",
    name: "empren dimiento",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 3,
    semester: 4,
    id: 24,
  },
  {
    code: "edd-001",
    name: "estructuras de datos",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 4,
    id: 25,
  },
  {
    code: "pdi-001",
    name: "proyecto diseño e innovación",
    department: "departamento de ingeniería industrial",
    credits: 4,
    semester: 4,
    id: 26,
  },
  {
    code: "elt-001",
    name: "electrotecnia",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 5,
    id: 27,
  },
  {
    code: "icd-001",
    name: "introducción a data science",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 5,
    id: 28,
  },
  {
    code: "dsd-001",
    name: "diseño de sistemas digitales",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 5,
    id: 29,
  },
  {
    code: "bdd-001",
    name: "bases de datos",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 5,
    id: 30,
  },
  {
    code: "epf-001",
    name: "electivo profesional i",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 5,
    id: 31,
  },
  {
    code: "ppa-001",
    name: "proyecto integrador programación avanzada",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 5,
    id: 32,
  },
  {
    code: "aoc-001",
    name: "arquitectura y organización de computadores",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 6,
    id: 33,
  },
  {
    code: "fdc-001",
    name: "fundamentos de la computación",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 6,
    id: 34,
  },
  {
    code: "iwm-001",
    name: "introducción al desarrollo web/móvil",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 6,
    id: 35,
  },
  {
    code: "isw-001",
    name: "ingeniería de software",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 6,
    id: 36,
  },
  {
    code: "epf-002",
    name: "electivo profesional ii",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 6,
    id: 37,
  },
  {
    code: "psw-001",
    name: "proyecto integrador software",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 6,
    id: 38,
  },
  {
    code: "sdi-001",
    name: "sistemas de información i",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 7,
    id: 39,
  },
  {
    code: "ldp-001",
    name: "lenguajes de programación",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 7,
    id: 40,
  },
  {
    code: "daa-001",
    name: "diseño y análisis de algoritmos",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 7,
    id: 41,
  },
  {
    code: "sop-001",
    name: "sistemas operativos",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 7,
    id: 42,
  },
  {
    code: "epf-003",
    name: "electivo profesional iii",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 7,
    id: 43,
  },
  {
    code: "dfc-002",
    name: "diálogo, fe y ciencia",
    department: "departamento de teología",
    credits: 2,
    semester: 7,
    id: 44,
  },
  {
    code: "ppf-001",
    name: "proyecto integrador plataformas",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 7,
    id: 45,
  },
  {
    code: "sdi-002",
    name: "sistemas de información ii",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 8,
    id: 46,
  },
  {
    code: "gpt-001",
    name: "gestión de proyectos ti",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 8,
    id: 47,
  },
  {
    code: "ads-001",
    name: "arquitectura de sistemas",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 8,
    id: 48,
  },
  {
    code: "rdc-001",
    name: "redes de computadores",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 8,
    id: 49,
  },
  {
    code: "epf-004",
    name: "electivo profesional iv",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 8,
    id: 50,
  },
  {
    code: "emp-001",
    name: "ética y moral profesional",
    department: "departamento de teología",
    credits: 2,
    semester: 8,
    id: 51,
  },
  {
    code: "pgt-001",
    name: "proyecto integrador gestión ti",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 8,
    id: 52,
  },
  {
    code: "ept-001",
    name: "evaluación de proyectos ti",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 9,
    id: 53,
  },
  {
    code: "epf-005",
    name: "electivo profesional v",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 9,
    id: 54,
  },
  {
    code: "epf-006",
    name: "electivo profesional vi",
    department: "departamento de ingeni   ería de sistemas y computación",
    credits: 5,
    semester: 9,
    id: 55,
  },
  {
    code: "epf-007",
    name: "electivo profesional vii",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 9,
    id: 56,
  },
  {
    code: "epf-008",
    name: "electivo profesional viii",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 9,
    id: 57,
  },
  {
    code: "epf-009",
    name: "electivo profesional ix",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 5,
    semester: 9,
    id: 58,
  },
  {
    code: "cpp-001",
    name: "capstone project",
    department: "departamento de ingeniería de sistemas y computación",
    credits: 30,
    semester: 10,
    id: 59,
  },
];
const careers = [
  {
    name: "arquitectura",
    id: 1,
  },
  {
    name: "ingeniería civil",
    id: 2,
  },
  {
    name: "ingeniería civil en gestión de la construcción",
    id: 3,
  },
  {
    name: "ingeniería civil plan común",
    id: 4,
  },
  {
    name: "ingeniería en construcción",
    id: 5,
  },
  {
    name: "analista químico",
    id: 6,
  },
  {
    name: "geología",
    id: 7,
  },
  {
    name: "licenciatura en física con mención en astronomía",
    id: 8,
  },
  {
    name: "licenciatura en matemática",
    id: 9,
  },
  {
    name: "química industrial",
    id: 10,
  },
  {
    name: "contador auditor - contador público diurno",
    id: 11,
  },
  {
    name: "contador auditor - contador público vespertino",
    id: 12,
  },
  {
    name: "ingeniería comercial",
    id: 13,
  },
  {
    name: "ingeniería en información y control de gestión",
    id: 14,
  },
  {
    name: "derecho",
    id: 15,
  },
  {
    name: "periodismo",
    id: 16,
  },
  {
    name: "psicología",
    id: 17,
  },
  {
    name: "ingeniería civil ambiental",
    id: 18,
  },
  {
    name: "ingeniería civil de minas",
    id: 19,
  },
  {
    name: "ingeniería civil electrónica",
    id: 20,
  },
  {
    name: "ingeniería civil en energía",
    id: 21,
  },
  {
    name: "ingeniería civil industrial",
    id: 22,
  },
  {
    name: "ingeniería civil metalúrgica",
    id: 23,
  },
  {
    name: "ingeniería civil plan común",
    id: 24,
  },
  {
    name: "ingeniería civil química",
    id: 25,
  },
  {
    name: "ingeniería en metalurgia",
    id: 26,
  },
  {
    name: "química industrial",
    id: 27,
  },
  {
    name: "pedagogía en educación básica con especialización",
    id: 28,
  },
  {
    name: "pedagogía en educación diferencial con mención en desarrollo emocional y cognitivo",
    id: 29,
  },
  {
    name: "pedagogía en educación parvularia con mención en desarrollo emocional y cognitivo",
    id: 30,
  },
  {
    name: "pedagogía en inglés",
    id: 31,
  },
  {
    name: "pedagogía en matemática en educación media",
    id: 32,
  },
  {
    name: "química y farmacia",
    id: 33,
  },
  {
    name: "ingeniería civil electrónica",
    id: 34,
  },
  {
    name: "ingeniería civil en computación e informática",
    id: 35,
  },
  {
    name: "ingeniería civil en energía",
    id: 36,
  },
  {
    name: "ingeniería civil plan común",
    id: 37,
  },
  {
    name: "ingeniería en computación e informática",
    id: 38,
  },
];
const subjectRelationships = [
  {
    subjectCode: "mec-001",
    preSubjectCode: "iaf-001",
    id: 1,
  },
  {
    subjectCode: "mec-001",
    preSubjectCode: "cal-001",
    id: 2,
  },
  {
    subjectCode: "cal-002",
    preSubjectCode: "cal-001",
    id: 3,
  },
  {
    subjectCode: "alg-002",
    preSubjectCode: "alg-001",
    id: 4,
  },
  {
    subjectCode: "prg-001",
    preSubjectCode: "alg-001",
    id: 5,
  },
  {
    subjectCode: "prg-001",
    preSubjectCode: "pri-001",
    id: 6,
  },
  {
    subjectCode: "ing-002",
    preSubjectCode: "ing-001",
    id: 7,
  },
  {
    subjectCode: "ecd-001",
    preSubjectCode: "cal-002",
    id: 8,
  },
  {
    subjectCode: "ecd-001",
    preSubjectCode: "alg-002",
    id: 9,
  },
  {
    subjectCode: "cal-003",
    preSubjectCode: "cal-002",
    id: 10,
  },
  {
    subjectCode: "poo-001",
    preSubjectCode: "prg-001",
    id: 11,
  },
  {
    subjectCode: "tpa-001",
    preSubjectCode: "prg-001",
    id: 12,
  },
  {
    subjectCode: "coe-002",
    preSubjectCode: "coe-001",
    id: 13,
  },
  {
    subjectCode: "dfc-001",
    preSubjectCode: "iue-001",
    id: 14,
  },
  {
    subjectCode: "elm-001",
    preSubjectCode: "cal-003",
    id: 15,
  },
  {
    subjectCode: "elm-001",
    preSubjectCode: "mec-001",
    id: 16,
  },
  {
    subjectCode: "elm-001",
    preSubjectCode: "alg-001",
    id: 17,
  },
  {
    subjectCode: "est-001",
    preSubjectCode: "cal-002",
    id: 18,
  },
  {
    subjectCode: "edd-001",
    preSubjectCode: "poo-001",
    id: 19,
  },
  {
    subjectCode: "edd-001",
    preSubjectCode: "tpa-001",
    id: 20,
  },
  {
    subjectCode: "pdi-001",
    preSubjectCode: "pii-001",
    id: 21,
  },
  {
    subjectCode: "elt-001",
    preSubjectCode: "ecd-001",
    id: 22,
  },
  {
    subjectCode: "icd-001",
    preSubjectCode: "est-001",
    id: 23,
  },
  {
    subjectCode: "icd-001",
    preSubjectCode: "edd-001",
    id: 24,
  },
  {
    subjectCode: "dsd-001",
    preSubjectCode: "alg-001",
    id: 25,
  },
  {
    subjectCode: "bdd-001",
    preSubjectCode: "edd-001",
    id: 26,
  },
  {
    subjectCode: "aoc-001",
    preSubjectCode: "dsd-001",
    id: 27,
  },
  {
    subjectCode: "fdc-001",
    preSubjectCode: "poo-001",
    id: 28,
  },
  {
    subjectCode: "fdc-001",
    preSubjectCode: "tpa-001",
    id: 29,
  },
  {
    subjectCode: "iwm-001",
    preSubjectCode: "bdd-001",
    id: 30,
  },
  {
    subjectCode: "isw-001",
    preSubjectCode: "edd-001",
    id: 31,
  },
  {
    subjectCode: "psw-001",
    preSubjectCode: "ppa-001",
    id: 32,
  },
  {
    subjectCode: "sdi-001",
    preSubjectCode: "bdd-001",
    id: 33,
  },
  {
    subjectCode: "ldp-001",
    preSubjectCode: "edd-001",
    id: 34,
  },
  {
    subjectCode: "daa-001",
    preSubjectCode: "fdc-001",
    id: 35,
  },
  {
    subjectCode: "sop-001",
    preSubjectCode: "aoc-001",
    id: 36,
  },
  {
    subjectCode: "dfc-002",
    preSubjectCode: "dfc-001",
    id: 37,
  },
  {
    subjectCode: "ppf-001",
    preSubjectCode: "psw-001",
    id: 38,
  },
  {
    subjectCode: "sdi-002",
    preSubjectCode: "sdi-001",
    id: 39,
  },
  {
    subjectCode: "gpt-001",
    preSubjectCode: "sdi-001",
    id: 40,
  },
  {
    subjectCode: "ads-001",
    preSubjectCode: "sop-001",
    id: 41,
  },
  {
    subjectCode: "rdc-001",
    preSubjectCode: "sop-001",
    id: 42,
  },
  {
    subjectCode: "emp-001",
    preSubjectCode: "dfc-002",
    id: 43,
  },
  {
    subjectCode: "pgt-001",
    preSubjectCode: "ppf-001",
    id: 44,
  },
  {
    subjectCode: "ept-001",
    preSubjectCode: "gpt-001",
    id: 45,
  },
  {
    subjectCode: "ept-001",
    preSubjectCode: "sdi-002",
    id: 46,
  },
];

async function seed() {
  const db = getDb();
  const subjectsCollection = db.collection("subjects");
  const careersCollection = db.collection("careers");
  const subjectRelationshipsCollection = db.collection("subjectRelationships");

  await subjectsCollection.insertMany(subjects);
  await careersCollection.insertMany(careers);
  await subjectRelationshipsCollection.insertMany(subjectRelationships);
}